export const ETHTOOL_STATS_COMMAND = "ethtool -S eth0" as const;
export const ETHTOOL_STATS_ETH3_COMMAND = "ethtool -S eth3" as const;

export const KNOWN_COMMANDS = [
  "ibstat",
  "show proposal a",
  "show proposal b",
  "show topology",
  "show rdma links",
  "show switch port rail0",
  "show switch port rail1",
  "show switch port rail2",
  "show switch port rail3",
  "show switch port rail4",
  "show switch port rail5",
  "show switch port rail6",
  "show switch port rail7",
  "show interface swp1",
  "show interface swp2",
  "show interface swp3",
  "show interface swp4",
  "show interface swp5",
  "show interface swp6",
  "show interface swp7",
  "show interface swp8",
  "show interface swp9",
  "show dcb pfc",
  "show dcb ets",
  "show dcb load-balance",
  "show ecmp load-balance",
  "show nccl env",
  "show interface counters",
  "show interfaces ib status",
  "show ib counters",
  ETHTOOL_STATS_COMMAND,
  ETHTOOL_STATS_ETH3_COMMAND,
  "nccl-debug --transport",
  "rdma link show",
  "run nccl-tests",
  "calculate oversubscription a",
  "calculate oversubscription b",
  "compare proposals",
  "recommend proposal a",
  "recommend proposal b",
  "recommend proposal",
  "show roce",
  "disable pfc",
  "enable pfc",
  "enable ecn",
  "enable load-balance per-packet",
  "disable ecn",
  "set nccl ib-hca",
  "set nccl ib-hca mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7",
  "set nccl socket-ifname",
  "set nccl socket-ifname eno1",
  "clear counters",
  "help",
  "hint",
  "ping",
  "ip a",
  "ip addr",
  "ip link",
  "ip link show",
  "export",
] as const;

export const KNOWN_VERBS = [
  "show",
  "disable",
  "enable",
  "no",
  "clear",
  "set",
  "help",
  "hint",
  "ethtool",
  "rdma",
  "ping",
  "ip",
  "export",
  "run",
  "nccl-debug",
] as const;
