export const ETHTOOL_STATS_COMMAND = "ethtool -S eth0" as const;
export const ETHTOOL_STATS_ETH3_COMMAND = "ethtool -S eth3" as const;
export const ETHTOOL_STATS_ETH2_COMMAND = "ethtool -S eth2" as const;
export const ETHTOOL_STATS_ETH5_COMMAND = "ethtool -S eth5" as const;

export const KNOWN_COMMANDS = [
  "ibstat",
  "show fabric health",
  "show bgp summary",
  "show bgp route 10.4.0.0/16",
  "show bgp route 10.4.0.0/16 detail",
  "show bgp route 10.2.0.0/16",
  "show bgp route 10.2.0.0/16 after",
  "show ip route 10.4.0.0/16",
  "show ip route 10.2.0.0/16",
  "show bgp neighbors 10.0.0.1",
  "show bgp neighbors 10.0.0.2",
  "show bgp link-bandwidth",
  "show proposal a",
  "show proposal b",
  "show topology",
  "show rdma links",
  "show switch port rail0",
  "show switch port rail1",
  "show switch port rail2",
  "show switch port rail3",
  "show switch port rail4",
  "show switch port rail5",
  "show switch port rail6",
  "show switch port rail7",
  "show interface swp1",
  "show interface swp2",
  "show interface swp3",
  "show interface swp4",
  "show interface swp5",
  "show interface swp6",
  "show interface swp7",
  "show interface swp8",
  "show interface swp9",
  "show dcb pfc",
  "show dcb ets",
  "show dcb load-balance",
  "show ecmp load-balance",
  "show nccl env",
  "show ufm ports",
  "show ufm alarms",
  "show ufm events",
  "show ufm port leaf-rail5 swp7",
  "show ufm topology",
  "show dcgm gpu5",
  "show dcgm all",
  "show pfc pause-stats",
  "show interface counters",
  "show interfaces ib status",
  "show ib counters",
  ETHTOOL_STATS_COMMAND,
  ETHTOOL_STATS_ETH2_COMMAND,
  ETHTOOL_STATS_ETH3_COMMAND,
  ETHTOOL_STATS_ETH5_COMMAND,
  "nccl-debug --transport",
  "rdma link show",
  "run nccl-tests",
  "calculate oversubscription a",
  "calculate oversubscription b",
  "compare proposals",
  "recommend proposal a",
  "recommend proposal b",
  "recommend proposal",
  "show roce",
  "disable pfc",
  "enable pfc",
  "enable pfc priority 3",
  "enable ecn",
  "enable load-balance per-packet",
  "disable ecn",
  "set nccl ib-hca",
  "set nccl ib-hca mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7",
  "set nccl socket-ifname",
  "set nccl socket-ifname eno1",
  "set bgp link-bandwidth community 1200",
  "set bgp local-as 65000",
  "set bgp local-as 65000 spineb",
  "clear counters",
  "show interface counters after",
  "replace optic rail2",
  "no shutdown",
  "reseat connector leaf-rail5 swp7",
  "show isis neighbor",
  "show isis srv6 node",
  "show segment-routing srv6 sid",
  "show sr-te segment-list",
  "show sr-te policy",
  "show ip policy",
  "show route-map STEER-CHECKPOINT",
  "configure segment-list",
  "configure sr-te policy",
  "configure route-map dscp10",
  "apply route-map swp1-4",
  "show mtu",
  "show srv6 packets",
  "tcpdump srh swp1",
  "traceroute6 checkpoint dscp10",
  "traceroute6 nccl dscp26",
  "ping6 spine02 sid",
  "ping6 spine03 sid",
  "ping6 storage sid",
  "show ip route vrf STORAGE",
  "show mr info",
  "ibv_devinfo -d mlx5_0 -i 1",
  "show gid filter",
  "enable gid filter",
  "ibv_reg_mr rotate",
  "show mr info after",
  "rkey scan",
  "ibv_devinfo -d mlx5_0",
  "ibv_rc_pingpong -d mlx5_0 -g 1",
  "show qos trust dscp-map",
  "nv show interface swp1 qos",
  "show gvmi table",
  "show ufm pkey table",
  "set pkey tenanta 0x8001",
  "set pkey tenantb 0x8002",
  "nv --version",
  "cl-platform-info",
  "nv show interface",
  "nv show interface | grep -E \"swp|state\"",
  "decode-syseeprom",
  "cl-netstat",
  "ip link show | grep mtu",
  "nv show router bgp",
  "submit audit report",
  "nv set interface swp1-32 qos roce",
  "nv show qos roce",
  "nv show qos ecn profile roce",
  "nv show qos pfc",
  "nv show qos scheduler",
  "nv show interface swp1 counters pfc",
  "cl-resource-query",
  "ethtool -S swp1 | grep ecn",
  "ib_write_bw -d mlx5_0 --iters 5000 --size 65536 192.168.100.2",
  "ib_write_lat -d mlx5_0 --iters 10000 192.168.100.2",
  "ibv_rc_pingpong -d mlx5_0 -g 0 192.168.100.2",
  "ip link show eth0",
  "ethtool -S mlx5_0 | grep -E 'ecn|pfc|retry'",
  "nv set qos ecn profile roce min-threshold 500000",
  "nv set qos ecn profile roce max-threshold 1500000",
  "ib_write_bw -d mlx5_0 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_1 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_2 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_3 --iters 10000 --size 65536 192.168.100.2 &",
  "nv show interface swp1 counters",
  "help",
  "hint",
  "ping",
  "ip a",
  "ip addr",
  "ip link",
  "ip link show",
  "export",
] as const;

export const KNOWN_VERBS = [
  "show",
  "disable",
  "enable",
  "no",
  "clear",
  "configure",
  "apply",
  "set",
  "help",
  "hint",
  "ethtool",
  "rdma",
  "ping",
  "ip",
  "export",
  "run",
  "submit",
  "nccl-debug",
  "tcpdump",
  "traceroute6",
  "ping6",
  "ibv_devinfo",
  "ibv_rc_pingpong",
  "ib_write_bw",
  "ib_write_lat",
  "ibv_reg_mr",
  "nv",
  "cl-platform-info",
  "cl-netstat",
  "cl-resource-query",
] as const;
