export const ETHTOOL_STATS_COMMAND = "ethtool -S eth0" as const;
export const ETHTOOL_STATS_ETH1_COMMAND = "ethtool -S eth1" as const;
export const ETHTOOL_STATS_ETH3_COMMAND = "ethtool -S eth3" as const;
export const ETHTOOL_STATS_ETH2_COMMAND = "ethtool -S eth2" as const;
export const ETHTOOL_STATS_ETH5_COMMAND = "ethtool -S eth5" as const;

export const KNOWN_COMMANDS = [
  "ibstat",
  "show fabric health",
  "netq show ecmp",
  "netq check bgp",
  "show bgp summary",
  "show bgp route 10.4.0.0/16",
  "show bgp route 10.4.0.0/16 detail",
  "show bgp route 10.2.0.0/16",
  "show bgp route 10.2.0.0/16 after",
  "nv show vrf default router bgp address-family ipv4-unicast route 10.4.0.0/16",
  "nv show vrf default router bgp address-family ipv4-unicast route 10.2.0.0/16",
  "nv show router policy route-map UCMP-LEAF4 rule 10 set",
  "nv show vrf default router bgp neighbor 10.0.0.2",
  "show ip route 10.4.0.0/16",
  "show ip route 10.2.0.0/16",
  "show bgp neighbors 10.0.0.1",
  "show bgp neighbors 10.0.0.2",
  "show bgp link-bandwidth",
  "show proposal a",
  "show proposal b",
  "cat proposal-a.txt",
  "cat proposal-b.txt",
  "show topology",
  "show rdma links",
  "show switch port rail0",
  "show switch port rail1",
  "show switch port rail2",
  "show switch port rail3",
  "show switch port rail4",
  "show switch port rail5",
  "show switch port rail6",
  "show switch port rail7",
  "show interface swp1",
  "show interface swp2",
  "show interface swp3",
  "show interface swp4",
  "show interface swp5",
  "show interface swp6",
  "show interface swp7",
  "show interface swp8",
  "show interface swp9",
  "show dcb pfc",
  "show dcb ets",
  "show dcb load-balance",
  "show ecmp load-balance",
  "show nccl env",
  "env | grep '^NCCL_'",
  "show ufm ports",
  "show ufm alarms",
  "show ufm events",
  "show ufm port leaf-rail5 swp7",
  "show ufm topology",
  "show dcgm gpu5",
  "show dcgm all",
  "dcgmi dmon -i 5 -c 1",
  "dcgmi dmon -i 5 -c 1 -e 1001,1004,1005",
  "show pfc pause-stats",
  "nv show interface swp7 counters qos pfc-stats",
  "ethtool -S swp7",
  "curl -ks 'https://ufm-server/ufmRest/resources/ports?high_ber_only=true&active=true'",
  "curl -ks 'https://ufm-server/ufmRest/resources/ports?system=leaf-rail5&active=true'",
  "show interface counters",
  "show interfaces ib status",
  "show ib counters",
  ETHTOOL_STATS_COMMAND,
  ETHTOOL_STATS_ETH1_COMMAND,
  ETHTOOL_STATS_ETH2_COMMAND,
  ETHTOOL_STATS_ETH3_COMMAND,
  ETHTOOL_STATS_ETH5_COMMAND,
  "nccl-debug --transport",
  "rdma link show",
  "run nccl-tests",
  "NCCL_DEBUG=INFO mpirun -np 128 -N 8 /opt/nccl-tests/build/all_reduce_perf -b 8G -e 8G -f 2 -g 1",
  "calculate oversubscription a",
  "calculate oversubscription b",
  "python3 fabric-sizing.py --proposal a",
  "python3 fabric-sizing.py --proposal b",
  "compare proposals",
  "python3 fabric-sizing.py --compare",
  "recommend proposal a",
  "recommend proposal b",
  "recommend proposal",
  "python3 fabric-sizing.py --recommend a",
  "python3 fabric-sizing.py --recommend b",
  "python3 fabric-sizing.py --recommend",
  "show roce",
  "disable pfc",
  "enable pfc",
  "enable pfc priority 3",
  "enable ecn",
  "enable load-balance per-packet",
  "disable ecn",
  "set nccl ib-hca",
  "set nccl ib-hca mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7",
  "set nccl socket-ifname",
  "set nccl socket-ifname eno1",
  "export NCCL_IB_HCA=mlx5_0:1,mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1",
  "export NCCL_SOCKET_IFNAME=eno1",
  "set bgp link-bandwidth community 1200",
  "set bgp local-as 65000",
  "set bgp local-as 65000 spineb",
  "nv set router policy route-map UCMP-LEAF4 rule 10 set ext-community-bw multipaths",
  "nv set router bgp autonomous-system 65000",
  "clear counters",
  "show interface counters after",
  "replace optic rail2",
  "no shutdown",
  "sudo ./ops/replace-osfp.sh leaf-rail2 swp3",
  "sudo ip link set swp3 protodown_reason linkflap off",
  "sudo ip link set swp3 protodown off",
  "reseat connector leaf-rail5 swp7",
  "sudo ./ops/reseat-dac.sh leaf-rail5 swp7",
  "show isis neighbor",
  "show isis srv6 node",
  "show isis segment-routing srv6 node",
  "show segment-routing srv6 sid",
  "show sr-te segment-list",
  "show sr-te policy",
  "show ip policy",
  "show route-map STEER-CHECKPOINT",
  "show route-map SET_SR_POLICY",
  "configure segment-list",
  "configure sr-te policy",
  "configure route-map dscp10",
  "apply route-map swp1-4",
  "sudo vtysh -f /etc/frr/checkpoint-segment-list.conf",
  "sudo vtysh -f /etc/frr/checkpoint-srte-policy.conf",
  "sudo vtysh -f /etc/frr/checkpoint-color-route-map.conf",
  "show mtu",
  "show srv6 packets",
  "tcpdump srh swp1",
  "traceroute6 checkpoint dscp10",
  "traceroute6 nccl dscp26",
  "traceroute 10.100.0.1",
  "traceroute 10.20.0.11",
  "ping6 spine02 sid",
  "ping6 spine03 sid",
  "ping6 storage sid",
  "ping -6 2001:db8:0:spine02::1 -c 3",
  "ping -6 2001:db8:0:spine03::1 -c 3",
  "ping -6 2001:db8:0:lsrv::100 -c 3",
  "sudo tcpdump -ni swp1 'ip6 and ip6[6] == 43' -c 20",
  "show ip route vrf STORAGE",
  "show mr info",
  "ibv_devinfo -d mlx5_0 -i 1",
  "show gid filter",
  "enable gid filter",
  "ibv_reg_mr rotate",
  "show mr info after",
  "rkey scan",
  "ibv_devinfo -d mlx5_0",
  "ibv_rc_pingpong -d mlx5_0 -g 1",
  "show qos trust dscp-map",
  "nv show qos trust dscp-map",
  "nv show qos roce prio-map",
  "nv show interface swp1 qos",
  "nv show interface swp1 qos roce status",
  "nv show interface swp1 qos roce status pool-map",
  "nv show interface swp1 qos roce counters",
  "show gvmi table",
  "show ufm pkey table",
  "set pkey tenanta 0x8001",
  "set pkey tenantb 0x8002",
  "curl -ks 'https://ufm-server/ufmRest/resources/pkeys/0x8001'",
  "curl -ks 'https://ufm-server/ufmRest/resources/pkeys/0x8002'",
  "curl -ks -X PUT 'https://ufm-server/ufmRest/resources/pkeys/0x8001/guids/506b4b0300a1b200'",
  "curl -ks -X PUT 'https://ufm-server/ufmRest/resources/pkeys/0x8002/guids/506b4b0300a1b202'",
  "nv --version",
  "cat /etc/lsb-release",
  "cl-platform-info",
  "nv show platform",
  "nv show interface",
  "nv show interface | grep -E \"swp|state\"",
  "decode-syseeprom",
  "cl-netstat",
  "sudo cl-netstat",
  "ip link show | grep mtu",
  "ip -br link show",
  "ip -br link show | grep swp",
  "nv show router bgp",
  "submit audit report",
  "nv set interface swp1-32 qos roce",
  "nv set qos roce",
  "nv set qos congestion-control default-global traffic-class 3 ecn enabled",
  "nv config apply",
  "nv config save",
  "nv show interface status",
  "nv show qos roce",
  "nv show interface swp1 qos pfc",
  "nv show interface swp1 counters qos pfc-stats",
  "nv show qos congestion-control default-global",
  "nv show qos congestion-control default-global traffic-class 3",
  "nv show router adaptive-routing",
  "nv show router adaptive-routing detail",
  "nv show router adaptive-routing resilient-hash",
  "nv show interface swp1 link stats",
  "nv show interface swp49 adaptive-routing",
  "nv show interface swp50 adaptive-routing",
  "nv show interface swp51 adaptive-routing",
  "nv show interface swp52 adaptive-routing",
  "nv show interface swp1 adaptive-routing",
  "nv show interface swp2 adaptive-routing",
  "nv show interface swp3 adaptive-routing",
  "nv show interface swp4 adaptive-routing",
  "nv show interface swp51 link stats",
  "nv show interface swp52 link stats",
  "nv show interface swp53 link stats",
  "nv show interface swp54 link stats",
  "nv show interface swp4 link stats",
  "nv show interface swp51 router adaptive-routing",
  "net show counters",
  "net show interface",
  "nv show qos ecn profile roce",
  "nv show qos pfc",
  "nv show qos scheduler",
  "nv show interface swp1 link",
  "nv show interface swp2 link",
  "nv show interface swp3 link",
  "nv show interface swp4 link",
  "nv show interface swp5 link",
  "nv show interface swp6 link",
  "nv show interface swp7 link",
  "nv show interface swp8 link",
  "nv show interface swp9 link",
  "nv show interface swp2 link flap-protection",
  "nv show interface swp3 link flap-protection",
  "nv show interface swp4 link flap-protection",
  "nv show interface swp5 link flap-protection",
  "nv show interface swp6 link flap-protection",
  "nv show interface swp7 link flap-protection",
  "nv show interface swp8 link flap-protection",
  "nv show interface swp9 link flap-protection",
  "nv show interface swp1 counters pfc",
  "cl-resource-query",
  "sudo cl-resource-query",
  "mlxlink -d /dev/mst/mt41692_pciconf0 --show_module | grep -i reorder",
  "mlxconfig -d /dev/mst/mt41692_pciconf0 q ROCE_REORDER_BUFFER_SIZE",
  "nv show interface eth0 reorder-buffer",
  "nv show interface eth1 reorder-buffer",
  "ethtool -S swp1 | grep ecn",
  "ib_write_bw -d mlx5_0 --iters 5000 --size 65536 192.168.100.2",
  "ib_write_bw -d mlx5_0 -x 3 --report_gbits -D 30 -q 16 10.100.1.2",
  "ib_write_lat -d mlx5_0 --iters 10000 192.168.100.2",
  "ibv_rc_pingpong -d mlx5_0 -g 0 192.168.100.2",
  "ip link show eth0",
  "ip link show eth1",
  "ethtool -S mlx5_0 | grep -E 'ecn|pfc|retry'",
  "ethtool -S eth0 | grep -E 'ecn|pfc|retry'",
  "nv set qos ecn profile roce min-threshold 500000",
  "nv set qos ecn profile roce max-threshold 1500000",
  "nv set qos congestion-control default-global traffic-class 3 min-threshold 500000",
  "nv set qos congestion-control default-global traffic-class 3 max-threshold 1500000",
  "nv set interface swp51 router adaptive-routing enable on",
  "nv set interface swp52 router adaptive-routing enable on",
  "nv set interface swp53 router adaptive-routing enable on",
  "nv set interface swp54 router adaptive-routing enable on",
  "nv set router adaptive-routing mode per-packet",
  "nv set router adaptive-routing mode per-flowlet",
  "nv set router adaptive-routing flowlet-timer 100us",
  "nv set router adaptive-routing flowlet-timer 1s",
  "nv set interface eth0 reorder-buffer enable",
  "nv set interface eth1 reorder-buffer enable",
  "ib_write_bw -d mlx5_0 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_1 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_2 --iters 10000 --size 65536 192.168.100.2 &",
  "ib_write_bw -d mlx5_3 --iters 10000 --size 65536 192.168.100.2 &",
  "help",
  "hint",
  "ping",
  "ip a",
  "ip addr",
  "ip link",
  "ip link show",
  "export",
] as const;

export const KNOWN_VERBS = [
  "show",
  "disable",
  "enable",
  "no",
  "clear",
  "configure",
  "apply",
  "set",
  "help",
  "hint",
  "ethtool",
  "rdma",
  "ping",
  "ip",
  "env",
  "export",
  "mpirun",
  "run",
  "cat",
  "curl",
  "dcgmi",
  "python3",
  "sudo",
  "net",
  "submit",
  "nccl-debug",
  "tcpdump",
  "traceroute",
  "traceroute6",
  "ping6",
  "ibv_devinfo",
  "ibv_rc_pingpong",
  "ib_write_bw",
  "ib_write_lat",
  "ibv_reg_mr",
  "nv",
  "netq",
  "cl-platform-info",
  "cl-netstat",
  "cl-resource-query",
  "mlxlink",
  "mlxconfig",
] as const;
