import type { DeviceType } from '@/types'

export const DEVICE_COMMANDS: Record<DeviceType, string[]> = {
  dgx: [
    'ibstat',
    'show fabric health',
    'rdma link show',
    'show proposal a',
    'show proposal b',
    'nccl-debug --transport',
    'show nccl env',
    'show dcgm gpu5',
    'show dcgm all',
    'run nccl-tests',
    'calculate oversubscription a',
    'calculate oversubscription b',
    'compare proposals',
    'recommend proposal a',
    'recommend proposal b',
    'recommend proposal',
    'set nccl ib-hca',
    'set nccl socket-ifname',
    'show topology',
    'traceroute6 checkpoint dscp10',
    'traceroute6 nccl dscp26',
    'ping6 spine02 sid',
    'ping6 spine03 sid',
    'ping6 storage sid',
    'show rdma links',
    'ethtool -S eth0',
    'ethtool -S eth2',
    'ethtool -S eth5',
    'help',
    'hint',
  ],
  'leaf-switch': [
    'show bgp summary',
    'show bgp route 10.4.0.0/16',
    'show bgp route 10.4.0.0/16 detail',
    'show bgp route 10.2.0.0/16',
    'show bgp route 10.2.0.0/16 after',
    'show ip route 10.4.0.0/16',
    'show ip route 10.2.0.0/16',
    'show ip route vrf STORAGE',
    'show ip policy',
    'show route-map STEER-CHECKPOINT',
    'show isis neighbor',
    'show isis srv6 node',
    'show segment-routing srv6 sid',
    'show sr-te segment-list',
    'show sr-te policy',
    'show mtu',
    'show dcb pfc',
    'show dcb ets',
    'show dcb load-balance',
    'show interface counters',
    'show interface swp1',
    'show interface swp2',
    'show interface swp3',
    'show interface swp4',
    'show interface swp5',
    'show interface swp6',
    'show interface swp7',
    'show interface swp8',
    'show interface swp9',
    'show pfc pause-stats',
    'show roce',
    'show switch port rail0',
    'show switch port rail1',
    'show switch port rail2',
    'show switch port rail3',
    'show switch port rail4',
    'show switch port rail5',
    'show switch port rail6',
    'show switch port rail7',
    'show interfaces ib status',
    'show ib counters',
    'disable pfc',
    'enable pfc',
    'enable pfc priority 3',
    'enable ecn',
    'enable load-balance per-packet',
    'disable ecn',
    'clear counters',
    'replace optic rail2',
    'no shutdown',
    'configure segment-list',
    'configure sr-te policy',
    'configure route-map dscp10',
    'apply route-map swp1-4',
    'help',
    'hint',
  ],
  'spine-switch': [
    'show bgp route 10.2.0.0/16',
    'show bgp neighbors 10.0.0.1',
    'show bgp neighbors 10.0.0.2',
    'show bgp link-bandwidth',
    'show interface counters',
    'show srv6 packets',
    'tcpdump srh swp1',
    'show interface counters after',
    'show interfaces ib status',
    'show ib counters',
    'show ib sm',
    'set bgp link-bandwidth community 1200',
    'set bgp local-as 65000',
    'set bgp local-as 65000 spineb',
    'help',
    'hint',
  ],
  'ufm-server': [
    'show topology',
    'show rdma links',
    'show ufm ports',
    'show ufm alarms',
    'show ufm events',
    'show ufm port leaf-rail5 swp7',
    'show ufm topology',
    'reseat connector leaf-rail5 swp7',
    'help',
    'hint',
  ],
}

export function getDeviceCommands(deviceType: DeviceType): string[] {
  return DEVICE_COMMANDS[deviceType] ?? []
}

export function isCommandAllowedOnDevice(
  command: string,
  deviceType: DeviceType,
): boolean {
  const allowed = DEVICE_COMMANDS[deviceType] ?? []
  const normalised = command.trim().toLowerCase()
  return allowed.some(
    (candidate) =>
      candidate.toLowerCase() === normalised
      || normalised.startsWith(candidate.toLowerCase()),
  )
}

export const DEVICE_PROMPTS: Record<DeviceType, string> = {
  dgx: 'dgx-node:~$',
  'leaf-switch': 'leaf-switch #',
  'spine-switch': 'spine-switch #',
  'ufm-server': 'ufm-server $',
}

export const DEVICE_OS_LABELS: Record<DeviceType, string> = {
  dgx: 'DGX OS (Ubuntu 22.04)',
  'leaf-switch': 'Cumulus Linux / Spectrum-X',
  'spine-switch': 'ONYX 3.11',
  'ufm-server': 'UFM 6.8',
}
