export function formatConditionLabel(key: string): string {
  const labels: Record<string, string> = {
    railIdentified: "Rail identified",
    linkConfirmed: "Link state confirmed",
    faultIsolated: "Fault isolated to switch port",
    pfcMissing: "PFC absence confirmed",
    pfcEnabled: "PFC enabled on switch",
    pfcVerified: "PFC verified with show dcb pfc",
    pfcDisabled: "PFC disabled",
    ecnEnabled: "ECN enabled",
    ecnVerified: "ECN verified",
    congestionChecked: "Congestion pattern identified",
    switchCountersChecked: "Switch counters checked",
    nicPauseConfirmed: "NIC-side pause storm confirmed",
    ecnMissingIdentified: "ECN absence identified as root cause",
    spineChecked: "Spine utilisation checked",
    lbModeIdentified: "Load balancing mode identified",
    lbEnabled: "Per-packet load balancing enabled",
    spineVerified: "Spine utilisation verified (balanced)",
    dropsConfirmed: "Packet drops confirmed on NIC",
    pfcPriorityInspected: "PFC priority field inspected",
    mismatchIdentified: "Priority mismatch identified",
    pfcPriorityFixed: "PFC reconfigured to priority 3",
    transportChecked: "NCCL transport identified",
    rdmaDevicesChecked: "RDMA devices verified",
    envVarIdentified: "Misconfigured env variable found",
    hcaFixed: "NCCL_IB_HCA corrected",
    socketFixed: "NCCL_SOCKET_IFNAME corrected",
    ncclVerified: "NCCL busbw verified (RDMA active)",
    proposalAInspected: "Proposal A inspected",
    proposalBInspected: "Proposal B inspected",
    oversubscriptionCalculated: "Oversubscription calculated",
    correctProposalIdentified: "Correct proposal identified",
    fabricHealthChecked: "Fabric health checked",
    ecmpImbalanceIdentified: "ECMP imbalance identified",
    bandwidthCommunityGapConfirmed: "Link-bandwidth community gap confirmed",
    bandwidthCommunityConfigured: "Link-bandwidth community configured",
    weightedEcmpVerified: "Weighted ECMP verified",
    failureScopeChecked: "Failure scope checked",
    suboptimalPathSeen: "Suboptimal path identified",
    sameAsnPrincipleIdentified: "Same-ASN spine principle identified",
    spineAAsnUnified: "Spine A ASN unified",
    spineBAsnUnified: "Spine B ASN unified",
    postFixPathVerified: "Post-fix path verification complete",
    nicActiveTrapSeen: "NIC Active trap recognised",
    errDisabledConfirmed: "Err-Disabled port confirmed",
    opticReplaced: "Optical transceiver replaced",
    portReenabled: "Port re-enabled with no shutdown",
    railVerified: "Rail recovery verified on both ends",
  };

  return labels[key] ?? key;
}
