export function formatConditionLabel(key: string): string {
  const labels: Record<string, string> = {
    railIdentified: "Rail identified",
    ufmRailMapChecked: "UFM rail map checked",
    hcaInventoryChecked: "DGX HCA inventory checked",
    rdmaNetdevMapChecked: "RDMA to netdev mapping checked",
    eth0StateChecked: "eth0 Linux link state checked",
    eth1StateChecked: "eth1 Linux link state checked",
    leafRail0PortChecked: "leaf-rail0 swp1 checked",
    leafRail1PortChecked: "leaf-rail1 swp1 checked",
    roceCounterProfileChecked: "RoCE profile checked on swp1",
    roceTrafficProbeRun: "ib_write_bw probe completed",
    switchPfcCountersRead: "Switch PFC counters read",
    switchRoceCountersRead: "Switch RoCE counters read",
    hostNicCountersRead: "Host NIC counters read",
    linkConfirmed: "Link state confirmed",
    faultIsolated: "Fault isolated to switch port",
    pfcMissing: "PFC absence confirmed",
    pfcEnabled: "PFC enabled on switch",
    pfcVerified: "PFC verified with show dcb pfc",
    pfcDisabled: "PFC disabled",
    ecnEnabled: "ECN enabled",
    ecnVerified: "ECN verified",
    congestionChecked: "Congestion pattern identified",
    switchCountersChecked: "Switch counters checked",
    nicPauseConfirmed: "NIC-side pause storm confirmed",
    ecnMissingIdentified: "ECN absence identified as root cause",
    spineChecked: "Spine utilisation checked",
    lbModeIdentified: "Load balancing mode identified",
    lbEnabled: "Per-packet load balancing enabled",
    spineVerified: "Spine utilisation verified (balanced)",
    dropsConfirmed: "Packet drops confirmed on NIC",
    pfcPriorityInspected: "PFC priority field inspected",
    mismatchIdentified: "Priority mismatch identified",
    pfcPriorityFixed: "PFC reconfigured to priority 3",
    transportChecked: "NCCL transport identified",
    rdmaDevicesChecked: "RDMA devices verified",
    envVarIdentified: "Misconfigured env variable found",
    hcaFixed: "NCCL_IB_HCA corrected",
    socketFixed: "NCCL_SOCKET_IFNAME corrected",
    ncclVerified: "NCCL busbw verified (RDMA active)",
    proposalAInspected: "Proposal A inspected",
    proposalBInspected: "Proposal B inspected",
    oversubscriptionCalculated: "Oversubscription calculated",
    correctProposalIdentified: "Correct proposal identified",
    fabricHealthChecked: "Fabric health checked",
    ecmpImbalanceIdentified: "ECMP imbalance identified",
    bandwidthCommunityGapConfirmed: "Link-bandwidth community gap confirmed",
    bandwidthCommunityConfigured: "Link-bandwidth community configured",
    weightedEcmpVerified: "Weighted ECMP verified",
    failureScopeChecked: "Failure scope checked",
    suboptimalPathSeen: "Suboptimal path identified",
    sameAsnPrincipleIdentified: "Same-ASN spine principle identified",
    spineAAsnUnified: "Spine A ASN unified",
    spineBAsnUnified: "Spine B ASN unified",
    postFixPathVerified: "Post-fix path verification complete",
    nicActiveTrapSeen: "NIC Active trap recognised",
    errDisabledConfirmed: "Err-Disabled port confirmed",
    opticReplaced: "Optical transceiver replaced",
    portReenabled: "Port re-enabled with no shutdown",
    railVerified: "Rail recovery verified on both ends",
    isisAdjVerified: "IS-IS adjacency and SID reachability verified",
    segmentListConfigured: "Segment list configured",
    srtePolicyActive: "SR-TE policy active",
    routeMapApplied: "Route-map applied to swp1-4",
    tracerouteVerified: "Traceroute confirmed SR-TE path",
    spine01Clean: "Spine-01 clean of checkpoint SRH",
    mrInspected: "Memory Region inspected",
    rkeyVulnerabilityReproduced: "RKEY exposure reproduced",
    gidFilteringIdentified: "GID filtering issue identified",
    gidFilteringEnabled: "GID filtering enabled",
    rkeyRotated: "RKEY rotated to a high-entropy value",
    attackBlocked: "Attack blocked after hardening",
    pkeyIsolationVerified: "PKey isolation verified in UFM",
    clVersionVerified: "Cumulus version and NVUE availability verified",
    portsAudited: "Physical port audit completed on all devices",
    asicHealthChecked: "ASIC identity and health counters checked",
    mtuVerified: "Server-facing MTU baseline verified",
    bgpClean: "BGP baseline confirmed clean",
    auditReportComplete: "Audit report completed",
  };

  return labels[key] ?? key;
}
